### PR TITLE
move the MoveAnything frames when moving/scaling any frames

### LINKED ISSUE #15: Moving the quest tracker causes glitches
Moving the quest tracker was dibbled because it caused glitches.

### PR DESCRIPTION
**Pull request by Numynum**
fixes #15 
changing the scale will still glitch the WorldQuestTracker addon frame position, but that's up to them to fix tbh; and it's not a totally random glitch

### CODE REVIEW

**Comment by zaCade** [comment]
Looks good to me, altho looks like you use spaces instead of tabs. I'd like that fixed :P

**Comment by Numynum** [comment]
heh, my bad :p

**Comment by zaCade** [comment]
Also, run the GetScale on the new local for frameToMove, instead of self.moveFrame

**Comment by Numynum** [comment]
that works for most frames; but the quest tracker frame won't actually rescale if you only scale the MoveAnything frame for some reason
that's why I figured simply rescaling both would be fine

**Comment by zaCade** [comment]
Scaling both might leave some unwanted side effects. Actually thought you replaced the scale, my bad on that one :P

**Comment by Numynum** [comment]
I agree it'd be nicer to only scale one of the frames
but in my testing, scaling just one would give an unwanted result
scaling the MoveAnything frame wouldn't scale the normal frame (making it look like nothing happened, apart from movement)
scaling the normal frame generally worked fine, but then the WQT frame would overlap (since it's tied to the non-scaled mover frame)

in the end it shouldn't have too many side effects, as long as both frames have the same scale

**Comment by zaCade** [comment]
Makes sense, +1

**Pull request merged**
